# EfficientNetB0 Frozen Baseline
# Phase 1: Train with frozen base to establish baseline

experiment_name: "EfficientNetB0 Frozen Baseline"
experiment_description: "Transfer learning with frozen EfficientNetB0 base, 20 epochs"
experiment_tags: ["baseline", "efficientnetb0", "transfer", "frozen"]

paths:
  data: "data/raw"
  artifacts: "artifacts"
  experiments: "experiments"

train:
  # Model architecture
  model_type: "transfer"
  base_model: "efficientnetb0"
  trainable_base: false  # Keep base frozen for baseline

  # Training parameters
  batch_size: 32
  epochs: 20
  learning_rate: 0.001
  optimizer: "adam"

  # Regularization
  dropout: 0.5

  # Early stopping
  early_stopping: true
  patience: 5

  # Data
  image_size: [224, 224]  # EfficientNetB0 uses 224x224
  num_classes: 120
