# EfficientNetB0 Transfer Learning - Modern Architecture
# Expected performance: 78-85% validation accuracy (best expected)

# Experiment metadata
experiment_name: "EfficientNetB0 Transfer Learning"
experiment_description: "Transfer learning with frozen EfficientNetB0 base, 20 epochs, modern efficient architecture"
experiment_tags: ["baseline", "efficientnet", "efficientnetb0", "transfer", "frozen"]

paths:
  data: "data/raw"
  artifacts: "artifacts"
  experiments: "experiments"

train:
  # Model architecture
  model_type: "transfer"
  base_model: "efficientnetb0"
  trainable_base: false   # Freeze base for initial training

  # Training parameters
  batch_size: 256  # Increased for better GPU utilization
  epochs: 20
  learning_rate: 0.001
  optimizer: "adam"

  # Regularization
  dropout: 0.5

  # Early stopping
  early_stopping: true
  patience: 5

  # Data
  image_size: [224, 224]
  num_classes: 120
