# VGG16 Transfer Learning - Comparison Experiment
# Expected performance: 72-79% validation accuracy

# Experiment metadata
experiment_name: "VGG16 Transfer Learning"
experiment_description: "Transfer learning with frozen VGG16 base, 20 epochs, comparison to ResNet50"
experiment_tags: ["baseline", "vgg16", "transfer", "frozen"]

paths:
  data: "data/raw"
  artifacts: "artifacts"
  experiments: "experiments"

train:
  # Model architecture
  model_type: "transfer"
  base_model: "vgg16"
  trainable_base: false   # Freeze base for initial training

  # Training parameters
  batch_size: 32
  epochs: 20
  learning_rate: 0.001
  optimizer: "adam"

  # Regularization
  dropout: 0.5

  # Early stopping
  early_stopping: true
  patience: 5

  # Data
  image_size: [224, 224]
  num_classes: 120
